name: Kiasmo
favicon: null
layout_spectrum: 0.09151
typography_spectrum: 0.68214
title: 'KIASMO      '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2320'
    - '#b1b6c2'
    - '#030206'
    - '#4d4c51'
    - '#837b88'
  brandStrength: 0.0625
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
