name: Quiasmo
favicon: null
layout_spectrum: 0.86092
typography_spectrum: 0.06757354643195868
title: 'Ni son todos los que están, ni están todos los que son'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.375
  lightness: 0.9101626011542976
  saturation: 0.23361222725361586
  rhythmicContrast: 0.2758504021912813
purpose: []
