name: Kiasmo
favicon: null
layout_spectrum: 0.3537632650695741
typography_spectrum: 0.36210495536215603
title: '   KIASMO'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.5992130904924124
  lightness: 0.9036294003017247
  saturation: 0.532395341899246
  rhythmicContrast: 0.3198080128058791
purpose: []
