name: Kiasmo
favicon: null
layout_spectrum: 0.09151
typography_spectrum: 0.68214
title: '   '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2320'
    - '#b1b6c2'
    - '#030206'
    - '#4d4c51'
    - '#837b88'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
