name: Quiasmo
favicon: null
layout_spectrum: 0.8537
typography_spectrum: 0.71706
title: 'KIASMONi son todos los que están, ni están todos los que son'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3f0fa'
    - '#513e37'
    - '#9aa9b2'
    - '#008abb'
    - '#1a0605'
  brandStrength: 0.625
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
