typography_spectrum: 0.36210495536215603
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.5992130904924124
  lightness: 0.9036294003017247
  saturation: 0.532395341899246
  rhythmicContrast: 0.3198080128058791
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3537632650695741
analytics:
  google: null
  facebook: null
  twitter: null
name: Kiasmo
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Cara A
    url: 'http//:allegory.blue'
    type: external
favicon: null
title: '   QUIASMO'
description: >-
  1. m. Ret. Disposición en órdenes inversos de los miembros de dos secuencias
  consecutivas
purpose: []
